//package com.university.attendance
//
//import com.google.firebase.firestore.Exclude
//import com.google.firebase.firestore.FieldValue
//import com.google.firebase.firestore.ServerTimestamp
//import java.util.Date
//
//data class ClassSchedule(
//
//    // Firestore document ID
//    @get:Exclude
//    @set:Exclude
//    var scheduleId: String = "",
//
//    // ============================================================
//    // TEACHER
//    // ============================================================
//
//    // Permanent Teacher ID generated by Admin
//    // Example: TCH-8F3K2A91
//    var teacherId: String = "",
//
//    // Teacher name saved for display
//    var teacherName: String = "",
//
//    // Firebase Auth UID is kept as an additional reference.
//    // It is NOT used as the primary schedule key.
//    var teacherAuthUid: String = "",
//
//    // ============================================================
//    // CLASS INFORMATION
//    // ============================================================
//
//    var className: String = "",
//
//    var subjectName: String = "",
//
//    var roomNumber: String = "",
//
//    // ============================================================
//    // DATE
//    // ============================================================
//
//    // yyyy-MM-dd
//    var date: String = "",
//
//    // Monday, Tuesday, etc.
//    var dayName: String = "",
//
//    // ============================================================
//    // TIME
//    // ============================================================
//
//    // Example: 09:00 AM
//    var startTime: String = "",
//
//    // Example: 10:00 AM
//    var endTime: String = "",
//
//    // ============================================================
//    // SEMESTER
//    // ============================================================
//
//    var semester: String = "",
//
//    // ============================================================
//    // NOTE
//    // ============================================================
//
//    var note: String = "",
//
//    // ============================================================
//    // ADMIN
//    // ============================================================
//
//    var createdBy: String = "Admin",
//
//    @ServerTimestamp
//    var createdAt: Date? = null
//
//) {
//
//    constructor() : this(scheduleId = "")
//
//    // ============================================================
//    // FIRESTORE MAP
//    // ============================================================
//
//    @Exclude
//    fun toMap(): Map<String, Any?> {
//
//        return mapOf(
//
//            // PRIMARY TEACHER IDENTIFIER
//            "teacherId" to teacherId,
//
//            // DISPLAY NAME
//            "teacherName" to teacherName,
//
//            // OPTIONAL AUTH REFERENCE
//            "teacherAuthUid" to teacherAuthUid,
//
//            // CLASS
//            "className" to className,
//            "subjectName" to subjectName,
//            "roomNumber" to roomNumber,
//
//            // DATE
//            "date" to date,
//            "dayName" to dayName,
//
//            // TIME
//            "startTime" to startTime,
//            "endTime" to endTime,
//
//            // SEMESTER
//            "semester" to semester,
//
//            // NOTE
//            "note" to note,
//
//            // ADMIN
//            "createdBy" to createdBy,
//
//            "createdAt" to FieldValue.serverTimestamp()
//        )
//    }
//}
package com.university.attendance

import com.google.firebase.firestore.Exclude
import com.google.firebase.firestore.FieldValue
import com.google.firebase.firestore.ServerTimestamp
import java.util.Date

data class ClassSchedule(

    // Firestore document ID
    @get:Exclude
    @set:Exclude
    var scheduleId: String = "",

    // ============================================================
    // TEACHER
    // ============================================================

    // Permanent Teacher ID generated by Admin
    // Example: TCH-8F3K2A91
    var teacherId: String = "",

    // Teacher name saved for display
    var teacherName: String = "",

    // Firebase Auth UID is kept as an additional reference.
    // It is NOT used as the primary schedule key.
    var teacherAuthUid: String = "",

    // ============================================================
    // CLASS INFORMATION
    // ============================================================

    var className: String = "",

    var subjectName: String = "",

    var roomNumber: String = "",

    // ============================================================
    // DATE
    // ============================================================

    // yyyy-MM-dd
    var date: String = "",

    // Monday, Tuesday, etc.
    var dayName: String = "",

    // ============================================================
    // TIME
    // ============================================================

    // Example: 09:00 AM
    var startTime: String = "",

    // Example: 10:00 AM
    var endTime: String = "",

    // ============================================================
    // SEMESTER
    // ============================================================

    var semester: String = "",

    // ============================================================
    // NOTE
    // ============================================================

    var note: String = "",

    // ============================================================
    // ADMIN
    // ============================================================

    var createdBy: String = "Admin",

    @ServerTimestamp
    var createdAt: Date? = null

) {

    // ============================================================
    // FIRESTORE MAP
    // ============================================================

    @Exclude
    fun toMap(): Map<String, Any?> {

        return mapOf(

            // PRIMARY TEACHER IDENTIFIER
            "teacherId" to teacherId,

            // DISPLAY NAME
            "teacherName" to teacherName,

            // OPTIONAL AUTH REFERENCE
            "teacherAuthUid" to teacherAuthUid,

            // CLASS
            "className" to className,
            "subjectName" to subjectName,
            "roomNumber" to roomNumber,

            // DATE
            "date" to date,
            "dayName" to dayName,

            // TIME
            "startTime" to startTime,
            "endTime" to endTime,

            // SEMESTER
            "semester" to semester,

            // NOTE
            "note" to note,

            // ADMIN
            "createdBy" to createdBy,

            "createdAt" to FieldValue.serverTimestamp()
        )
    }
}